services:
  order_service:
    build: .
    container_name: order_service
    ports:
      - "8002:8002"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    networks:
      - shoponbot_external_shared_net

networks:
  shoponbot_external_shared_net:
    external: true
    name: shoponbot-production-network 