services:
  order_service:
    build: .
    container_name: order_service
    expose:
      - "8002"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    networks:
      - shoponbot_external_shared_net

networks:
  shoponbot_external_shared_net:
    external: true
    name: shoponbot-production-network