"""remove currency and payment status column from orders table and create payments table

Revision ID: 5da9f3b53e07
Revises: e9f015c9ed67
Create Date: 2026-09-22 07:55:47.554498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5da9f3b53e07'
down_revision: Union[str, Sequence[str], None] = 'e9f015c9ed67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False, server_default="pending"),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'ONLINE', 'UPI', 'CARD', name='paymentmode'), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
