"""add_name_to_addresses table

Revision ID: 8a89d7ceb011
Revises: 06a924f8d4a3
Create Date: 2026-09-07 20:19:35.418537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a89d7ceb011'
down_revision: Union[str, Sequence[str], None] = '06a924f8d4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'name')
    # ### end Alembic commands ###
