"""add razorpay_order_id column in payments table

Revision ID: 97dc8eb8649d
Revises: 5da9f3b53e07
Create Date: 2026-09-23 07:30:25.101878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dc8eb8649d'
down_revision: Union[str, Sequence[str], None] = '5da9f3b53e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'payments', ['razorpay_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    
    op.drop_column('payments', 'razorpay_order_id')
    # ### end Alembic commands ###
