"""add_netbanking_to_payment_mode_enum

Revision ID: ff8271b25377
Revises: 97dc8eb8649d
Create Date: 2026-10-05 06:10:48.823472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8271b25377'
down_revision: Union[str, Sequence[str], None] = '97dc8eb8649d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE paymentmode ADD VALUE 'netbanking'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
